import {
  CakeIcon,
  ShoppingBagIcon,
  TvIcon,
  HomeIcon,
  HeartIcon,
  BankIcon,
} from "@heroicons/react/24/solid";
import { AiFillCar, AiFillBank } from "react-icons/ai";
import { MdSportsBasketball, MdOutlineRealEstateAgent } from "react-icons/md";
import { ImAirplane } from "react-icons/im";

//////////////////////

const businessDB = [
  {
    branchId: 1,
    branchName: "Véhicules & transport",
    branchIcon: <CakeIcon className="h-16" />,
    categories: [
      {
        CatId: 11,
        catName: "Véhicle Rental",
        icon: <AiFillCar className="h-5" />,
        businesses: [
          {
            businessId: 111,
            businessName: "Parkos",
            logo: "",
            address: "Rue amalou youcef, IMP AK , n°15,Bouarfa ",
            city: "Blida",
            zip: "09000",
            country: "Algerie",
            website: "www.parkos.com",
            industry: "Location véhicules avec ou sans chauffeurs",
            reviewsCount: 253,
            contact: {
              name: "Bahani Billel",
              email: "billel.bahani@gmail.com",
              phone: "0554 990 201",
            },
          },
          {
            businessId: 112,
            businessName: "Taj Mahal",
            logo: "",
            address: "Pancsheel Enclave, New Delhi",
            city: "New Delhi",
            zip: 110017,
            country: "India",
            website: "www.tajmahal.com",
            industry: "Hospitality",
            reviewsCount: 1756,
            contact: {
              name: "Rajesh Kumar",
              email: "rajesh@tajmahal.com",
              phone: "+91-11-6614-8888",
            },
          },
          {
            businessId: 113,
            businessName: "Sofa King",
            logo: "",
            address: "1234 Main Street",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.sofaking.com",
            industry: "Furniture",
            reviewsCount: 102,
            contact: {
              name: "John Smith",
              email: "john@sofaking.com",
              phone: "(123) 456-7890",
            },
          },
          {
            businessId: 114,
            businessName: "La Parisienne",
            logo: "",
            address: "10 Rue du Faubourg Saint-Honoré",
            city: "Paris",
            zip: 75008,
            country: "France",
            website: "www.laparisienne.com",
            industry: "Fashion",
            reviewsCount: 789,
            contact: {
              name: "Marie Dupont",
              email: "marie@laparisienne.com",
              phone: "+33 1 42 65 63 63",
            },
          },
          {
            businessId: 115,
            businessName: "Jungle Surf",
            logo: "",
            address: "Calle 20, Playa del Carmen",
            city: "Playa del Carmen",
            zip: 77710,
            country: "Mexico",
            website: "www.junglesurf.com",
            industry: "Surf Shop",
            reviewsCount: 45,
            contact: {
              name: "Juan Hernandez",
              email: "juan@junglesurf.com",
              phone: "+52 984 123 4567",
            },
          },
          {
            businessId: 116,
            businessName: "GreenThumb",
            logo: "",
            address: "100 Main Street",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.greenthumb.com",
            industry: "Landscaping",
            reviewsCount: 341,
            contact: {
              name: "Sarah Johnson",
              email: "sarah@greenthumb.com",
              phone: "(123) 456-7890",
            },
          },
        ],
      },
      {
        CatId: 12,
        catName: "Travel Agencies",
        icon: <ImAirplane className="h-5" />,
        businesses: [
          {
            businessId: 121,
            businessName: "Adventure Seekers",
            logo: "",
            address: "456 Main Street",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.adventureseekers.com",
            industry: "Travel Agency",
            reviewsCount: 67,
            contact: {
              name: "Emily Jones",
              email: "emily@adventureseekers.com",
              phone: "(123) 456-7890",
            },
          },
          {
            businessId: 122,
            businessName: "The Wanderlust",
            logo: "",
            address: "15 Rue des Rosiers",
            city: "Paris",
            zip: 75004,
            country: "France",
            website: "www.thewanderlust.com",
            industry: "Travel Agency",
            reviewsCount: 231,
            contact: {
              name: "Sophie Martin",
              email: "sophie@thewanderlust.com",
              phone: "+33 1 42 78 89 01",
            },
          },
          {
            businessId: 123,
            businessName: "Ocean Breeze",
            logo: "",
            address: "123 Ocean Blvd",
            city: "Miami Beach",
            zip: 33139,
            country: "USA",
            website: "www.oceanbreeze.com",
            industry: "Travel Agency",
            reviewsCount: 89,
            contact: {
              name: "Mike Williams",
              email: "mike@oceanbreeze.com",
              phone: "(305) 555-1212",
            },
          },
          {
            businessId: 124,
            businessName: "Safari Adventure",
            logo: "",
            address: "10 Bree Street",
            city: "Cape Town",
            zip: 8000,
            country: "South Africa",
            website: "www.safariadventure.com",
            industry: "Travel Agency",
            reviewsCount: 456,
            contact: {
              name: "Lerato Mabaso",
              email: "lerato@safariadventure.com",
              phone: "+27 21 555 1212",
            },
          },
          {
            businessId: 125,
            businessName: "The Island Hopper",
            logo: "",
            address: "4 Beach Road",
            city: "Phuket",
            zip: 83000,
            country: "Thailand",
            website: "www.theislandhopper.com",
            industry: "Travel Agency",
            reviewsCount: 124,
            contact: {
              name: "Samantha Lee",
              email: "samantha@theislandhopper.com",
              phone: "+66 76 555 1212",
            },
          },
        ],
      },
      {
        CatId: 13,
        catName: "Gyms and Fitness Centers",
        icon: <MdSportsBasketball className="h-5" />,
        businesses: [
          {
            businessId: 131,
            businessName: "Fit Life",
            logo: "",
            address: "456 Fitness Lane",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.fitlife.com",
            industry: "Gym",
            reviewsCount: 178,
            contact: {
              name: "Alex Rodriguez",
              email: "alex@fitlife.com",
              phone: "(123) 456-7890",
            },
          },
          {
            businessId: 132,
            businessName: "Powerhouse Gym",
            logo: "",
            address: "20 MarketStreet",
            city: "New York",
            zip: 10002,
            country: "USA",
            website: "www.powerhousegym.com",
            industry: "Gym",
            reviewsCount: 654,
            contact: {
              name: "John Doe",
              email: "johndoe@powerhousegym.com",
              phone: "+1 (212) 555-1234",
            },
          },
          {
            businessId: 133,
            businessName: "Yoga Bliss",
            logo: "",
            address: "789 Zen Way",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.yogabliss.com",
            industry: "Yoga Studio",
            reviewsCount: 245,
            contact: {
              name: "Jessica Smith",
              email: "jessica@yogabliss.com",
              phone: "(123) 456-7890",
            },
          },
          {
            businessId: 134,
            businessName: "Sweat Factory",
            logo: "",
            address: "678 Fitness Ave",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.sweatfactory.com",
            industry: "Gym",
            reviewsCount: 372,
            contact: {
              name: "Mike Johnson",
              email: "mike@sweatfactory.com",
              phone: "(123) 456-7890",
            },
          },
          {
            businessId: 135,
            businessName: "Pilates Pro",
            logo: "",
            address: "321 Wellness Rd",
            city: "Anytown",
            zip: 12345,
            country: "USA",
            website: "www.pilatespro.com",
            industry: "Pilates Studio",
            reviewsCount: 98,
            contact: {
              name: "Kate Williams",
              email: "kate@pilatespro.com",
              phone: "(123) 456-7890",
            },
          },
          {
            businessId: 136,
            businessName: "Muscle Works",
            logo: "",
            address: "10 Fitness Boulevard",
            city: "Los Angeles",
            zip: 90001,
            country: "USA",
            website: "www.muscleworks.com",
            industry: "Gym",
            reviewsCount: 532,
            contact: {
              name: "Steve Rogers",
              email: "steve@muscleworks.com",
              phone: "+1 (323) 555-1234",
            },
          },
        ],
      },
    ],
  },
];

export default businessDB;
