import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Navigation from "../components/Navigation";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sal Mdjareb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative">
        <nav className="absolute left-0 top-0 z-20">
          <Navigation />
        </nav>
        <Banner />
      </main>
    </div>
  );
}
