import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Home/Banner";
import ExploreCartegories from "../components/Home/ExploreCategories";
import Navigation from "../components/Navigation";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sal Mdjareb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen bg-lightOrange">
        <Banner />
        <ExploreCartegories />
      </main>
    </div>
  );
}
